### ISSUE TITLE
Publish emm-scalaz to maven

### ISSUE THREAD

**Issue by sscarduzio** [djspiewak/emm#10]
Hi Daniel, Shim is really neat. When will you apply it to emm? 
I need to depend on emm on a scalaz project :)

_S

**Comment by djspiewak** [comment]
Working on it now!  There are some weird corner cases which have to do with chained implicit resolution that I can't quite seem to get around (or at least, haven't yet).  Or maybe I'm just being derp.  :-)  If I can't figure it out within the next day or so, I'll push a wip/ branch up here so that more people can look at it and tell me if I'm just being dumb.

**Comment by djspiewak** [comment]
As of version `0.1-20afa3d`, we are publishing to Maven Central!  The following artifacts are relevant:
- `"com.codecommit" %% "emm-core" % "0.1-20afa3d"`
- `"com.codecommit" %% "emm-scalaz-71" % "0.1-20afa3d"`
- `"com.codecommit" %% "emm-scalaz-72" % "0.1-20afa3d"`

Which scalaz artifact you use depends on your upstream scalaz version.
