### ISSUE TITLE
Breaks laws; not consistent with Applicative

### ISSUE THREAD

**Issue by puffnfresh** [djspiewak/emm#4]
If we try to encode the idea of using a Traversable constraint to get "composable Monads" in Haskell:

``` haskell
module TraverseMonad where

import Control.Monad (ap, join)

newtype TraverseMonad t f a = TraverseMonad { unTraverseMonad :: t (f a) } deriving (Show, Eq)

instance (Functor t, Functor f) => Functor (TraverseMonad t f) where
  fmap f (TraverseMonad tfa) = TraverseMonad $ fmap (fmap f) tfa

instance (Applicative t, Applicative f) => Applicative (TraverseMonad t f) where
  pure = TraverseMonad . pure . pure
  TraverseMonad tff <*> TraverseMonad tfa = TraverseMonad $ (<*>) <$> tff <*> tfa

instance (Monad t, Monad f, Traversable f) => Monad (TraverseMonad t f) where
  return = pure
  TraverseMonad tfa >>= f = TraverseMonad $ tfa >>= fmap join . traverse (unTraverseMonad . f)
```

We'll notice the Functor and Applicative instances are exactly the same as [`Data.Functor.Compose`](https://hackage.haskell.org/package/transformers/docs/Data-Functor-Compose.html).

But when testing the Monad laws with QuickCheck, we can find a broken law:
- `(<*>) = ap` (i.e. `(<*>) = (\m1 m2 -> do { x1 <- m1; x2 <- m2; return (x1 x2) })`)

Here's the test, using `Maybe`:

``` haskell
{-# LANGUAGE FlexibleContexts #-}
module TraverseMonadCheck where

import TraverseMonad
import Test.QuickCheck

instance Arbitrary (t (f a)) => Arbitrary (TraverseMonad t f a) where
  arbitrary = TraverseMonad <$> arbitrary

apProp :: (Eq (m (a, b)), Monad m) => m a -> m b -> Bool
apProp tfa tfb = ((,) <$> tfa <*> tfb) == (((,) <$> tfa) `ap` tfb)

maybeApProp :: TraverseMonad Maybe Maybe Int -> TraverseMonad Maybe Maybe Char -> Bool
maybeApProp = apProp
```

Which gives the following counter-example:

```
tfa = TraverseMonad {unTraverseMonad = Just Nothing}
tfb = TraverseMonad {unTraverseMonad = Nothing}

TraverseMonad {unTraverseMonad = Nothing} = TraverseMonad {unTraverseMonad = Just Nothing}
```

I think the easiest way to resolve this is to create "CommutativeApplicative" and "CommutativeMonad" type-classes and those as constraints. The first would require the law that `fmap ($)` is identity on the left hand side of `<*>`. I think there'd be a bit more work on the Monad version.

**Comment by djspiewak** [comment]
Hmm, I need to digest this more.  I think this is a general version of what the [`ApplicativeSpecs`](https://github.com/djspiewak/emm/blob/master/src/test/scala/emm/ApplicativeSpecs.scala) are capturing with `List` and `Option`.

In the specific case of the code as it stands with `Emm`, the `Applicative` and `Monad` instances _are_ inconsistent, but this is actually invisible in all use-cases unless the user goes out of their way to reveal it (i.e. by violating typeclass coherence).  Because of the fact that `Monad[Emm[C, ?]]` implies a _specific_ `Applicative[Emm[C, ?]]` which is defined in terms of `>>=`, the two instances will be consistent for any `Emm[C, ?]` that has a `Monad`.  For `Emm[C, ?]` that do _not_ have a `Monad` (for example, `Emm[List |: Task |: Base, ?]`), there is an `Applicative` which is defined in terms of compose, and that applicative certainly has different semantics than what the monad would have _if it existed_… but it doesn't exist.

Thus, the only time when the compose applicative and the traverse monad are inconsistent is precisely the time at which the traverse monad shadows the compose applicative (in the case of `Emm`, this is done with low priority implicits).  The only _possible_ case I can think of where this could cause user-visible deviations in behavior is something like this:

``` scala
def foo[F[_]: Applicative, G[_]: Applicative, A](e1: Emm[F |: G |: Base, A], e2: Emm[F |: G |: Base, A) = {
  // stuff using Applicative[Emm[F |: G |: Base, ?]]
}
```

And then refactor this function – _without_ changing the definition – to the following:

``` scala
def foo[F[_]: Monad, G[_]: Monad: Traverse, A](e1: Emm[F |: G |: Base, A], e2: Emm[F |: G |: Base, A) = {
  // stuff using Applicative[Emm[F |: G |: Base, ?]]
}
```

If you do this, then the semantics of `foo` will change, which is _clearly_ a violation of the laws.  No argument there.  This doesn't strike me as a particularly plausible scenario though, and so while I would certainly rather avoid it (which is why your proposal seems intriguing), I don't think it's as scary as it otherwise would be.

**Comment by puffnfresh** [comment]
> ... particularly plausible scenario...

I think it's not only plausible but common.

**Comment by djspiewak** [comment]
> I think it's not only plausible but common.
1. At least one non-outer parametric effect within a transformer stack
2. Function using `Emm` defined solely in terms of `Applicative` (no `Monad`)
3. Same function modified to constrain parametric effect to `Monad` and `Traverse`, rather than `Applicative`

I'm honestly not convinced that's very common.  Again, I do realize I'm defending a violation of laws, but in all seriousness, I'd like to be walked through one of these common scenarios, because I just don't see it.

As a sidebar, you can replicate this same violation with plain-old `ListT` in Haskell.  No need to even bring in `Traverse`.  This scenario really can't be all that common, seeing as people generally don't even realize `ListT` is non-lawful, much less run into bugs as a consequence.

**Comment by djspiewak** [comment]
One more thought: this whole problem becomes moot if I change `Applicative` to `Functor` in `EmmLowPriorityImplicits1` – which I'm certainly not averse to doing if it's really irredeemable!  I'd just rather go wherever the least harm is to be done.

**Comment by puffnfresh** [comment]
@djspiewak that's a quick fix for this :+1: 

Are there any more Monad laws broken?

**Comment by djspiewak** [comment]
> Are there any more Monad laws broken?

None that I know of.  I haven't set up laws based testing, but it's on my todo list (PR very much welcome and indeed, solicited).

The inconsistency itself arises from the different methods of deriving the `Applicative`, one directly via function composition, and the other indirectly via `traverse` and `>>=`.  `Monad` and `Applicative` for a given type are constrained to be consistent with each other, but there are no laws (to my knowledge) which cover the properties of `traverse` relative to `>>=`, and even if there were, I'm not sure it would change anything.  This does suggest though that `ap` is probably the only function affected, since `map` doesn't involve `traverse` and `point` is trivial.

I'll swap the `Applicative` instance to `Functor` in the interests of paranoia, but I'd still be very interested in any realistic cases you can contrive which hit this.

**Comment by djspiewak** [comment]
I'm going to close this now, since we dealt with the `Applicative` issue.  Having had more time to think about it, I think that solely exposing `Functor` resolves the problem nicely.  As a sidebar, this is an interesting case where `Pointed` would be a useful typeclass, since `Emm` can define `point` and `map`, just not `ap`.
